---
title: "project2_biologist"
output: word_document
---


```{r}

library(dplyr)
setwd("/projectnb/bf528/users/group_5/project_2/evie")
fpkm <- read.table('fpkm_matrix.csv', header=TRUE, sep="\t")
Gdiff <- read.table("/projectnb/bf528/users/group_5/project_2/cuffdiff_out/gene_exp.diff", header=TRUE)
dav_down5 <- read.csv("DAVID_down_top5.csv")
dav_up5 <- read.csv("DAVID_up_top5.csv")
sig_down <- read.csv("sig_genes_down.csv")

#read fpkm tracking tables 
P0_2 <- read.csv("/project/bf528/project_2/data/samples/P0_2/genes.fpkm_tracking", header=TRUE, sep="\t") #%>% rename(FPKM_P02 = FPKM)
P0_1 <- read.csv("/projectnb/bf528/users/group_5/project_2/evie/genes.fpkm_tracking", header=TRUE, sep="\t") 
P4_1 <- read.csv("/project/bf528/project_2/data/samples/P4_1/genes.fpkm_tracking", header=TRUE, sep="\t") 
P4_2 <- read.csv("/project/bf528/project_2/data/samples/P4_2/genes.fpkm_tracking", header=TRUE, sep="\t")
P7_1 <- read.csv("/project/bf528/project_2/data/samples/P7_1/genes.fpkm_tracking", header=TRUE, sep="\t")
P7_2 <- read.csv("/project/bf528/project_2/data/samples/P7_2/genes.fpkm_tracking", header=TRUE, sep="\t")

Ad1_ftable <-read.csv("/project/bf528/project_2/data/samples/Ad_1/genes.fpkm_tracking", header=TRUE, sep="\t")
Ad2_ftable <- read.csv("/project/bf528/project_2/data/samples/Ad_2/genes.fpkm_tracking", header=TRUE, sep="\t")

```

#Sacromere
```{r}
library(tibble)
#Sacromere Gene names
genes_sac <- c("Pdlim5", "Pygm", "Myoz2", "Des", "Csrp3", "Tcap", "Cryab")
genes_mit <- c("Mpc1", "Prdx3", "Acat1", "Echs1", "Slc25a11", "Phyh")
genes_cc <- c("Cdc7", "E2f8", "Cdk7", "Cdc26", "Cdc6", "Cdc27", "Bora", "Cdc45", "Rad51", "Aurkb", "Cdc23")

#filter adult sacromere genes 

sacromere_ad1 <- Ad1_ftable %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name") 
sacromere_ad2 <- Ad2_ftable %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

ad_com <- cbind(sacromere_ad1, sacromere_ad2$FPKM)
ad_com$mean <- rowMeans(ad_com) 
ad_mean <- ad_com %>% rownames_to_column("Genes")
ad_sacro <- data.frame("Genes" = ad_mean$Genes, "FPKM" = ad_mean$mean, "Status" = c("Ad", "Ad", "Ad","Ad", "Ad", "Ad","Ad"))
```


```{r}
#filter P0 sacromere genes
sacromere_p0 <- P0_1 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")
sacromere_p02 <- P0_2 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")
p0_com <- cbind(sacromere_p0, sacromere_p02$FPKM)

p0_com$mean <- rowMeans(p0_com)
p0_mean <- p0_com %>% rownames_to_column("Genes")

p0_sacro <- data.frame("Genes" = p0_mean$Genes, "FPKM" = p0_mean$FPKM, "Status" = c("P0", "P0","P0", "P0","P0", "P0","P0"))
```

```{r}
#filter P4
sacromere_p41 <- P4_1 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name") 
sacromere_p42 <- P4_2 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p4_com <- cbind(sacromere_p41, sacromere_p42$FPKM)
p4_com$mean <- rowMeans(p4_com) 
p4_mean <- p4_com %>% rownames_to_column("Genes")
p4_sacro <- data.frame("Genes" = p4_mean$Genes, "FPKM" = p4_mean$mean, "Status" = c("P4", "P4", "P4", "P4","P4", "P4","P4"))
```


```{r}
#filter P7
sacromere_p71 <- P7_1 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name") 
sacromere_p72 <- P7_2 %>% filter(gene_short_name %in% genes_sac) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p7_com <- cbind(sacromere_p71, sacromere_p72$FPKM)
p7_com$mean <- rowMeans(p7_com) 
p7_mean <- p7_com %>% rownames_to_column("Genes")
p7_sacro <- data.frame("Genes" = p7_mean$Genes, "FPKM" = p7_mean$mean, "Status" = c("P7", "P7", "P7", "P7","P7", "P7","P7"))

sac_fin <- bind_rows(p0_sacro, p4_sacro, p7_sacro, ad_sacro)
```



#Mitochondria
```{r}
#filter P0 mitochondira genes

mit_p01 <- P0_1 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

mit_p02 <- P0_2 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p0mit_com <- cbind(mit_p01, mit_p02)
p0mit_com$mean <- rowMeans(p0mit_com)
p0mit_mean <- p0mit_com %>% rownames_to_column("Genes")
p0_mit <- data.frame("Genes" = p0mit_mean$Genes, "FPKM" = p0mit_mean$FPKM, "Status" = c("P0","P0","P0","P0","P0"))

```



```{r}
#filter P4 mitocondria 

mit_p41 <- P4_1 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

mit_p42 <- P4_2 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p4mit_com <- cbind(mit_p41, mit_p42)
p4mit_com$mean <- rowMeans(p4mit_com)
p4mit_mean <- p4mit_com %>% rownames_to_column("Genes")

p4_mit <-  data.frame("Genes" = p4mit_mean$Genes, "FPKM" = p4mit_mean$FPKM, "Status"=c("P4", "P4","P4", "P4","P4"))

```

```{r}
#filter P7 mitocondria 
mit_p71 <- P7_1 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

mit_p72 <- P7_2 %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p7mit_com <- cbind(mit_p71, mit_p72)
p7mit_com$mean <- rowMeans(p7mit_com)
p7mit_mean <- p7mit_com %>% rownames_to_column("Genes")

p7_mit <-  data.frame("Genes" = p7mit_mean$Genes, "FPKM" = p7mit_mean$FPKM, "Status"=c("P7", "P7","P7", "P7","P7"))

```

```{r}
#filter Ad mitchondria 
mit_ad1 <- Ad1_ftable %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name") 
mit_ad2 <- Ad2_ftable %>% filter(gene_short_name %in% genes_mit) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

admit_com <- cbind(mit_ad1, mit_ad2$FPKM)
admit_com$mean <- rowMeans(admit_com) 
admit_mean <- admit_com %>% rownames_to_column("Genes")
ad_mit <- data.frame("Genes" = admit_mean$Genes, "FPKM" = admit_mean$mean, "Status" = c("Ad", "Ad","Ad", "Ad","Ad"))
mit_fin <- bind_rows(p0_mit, p4_mit, p7_mit, ad_mit)
```


#Cell Cycle
```{r}
#filter P0 cell cycle genes

cc_p01 <- P0_1 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

cc_p02 <- P0_2 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p0cc_com <- cbind(cc_p01, cc_p02)
p0cc_com$mean <- rowMeans(p0cc_com)
p0cc_mean <- p0cc_com %>% rownames_to_column("Genes")
p0_cc <- data.frame("Genes" = p0cc_mean$Genes, "FPKM" = p0cc_mean$FPKM, "Status" = c("P0","P0","P0","P0","P0"))
```


```{r}
#filter P4 cell cycle genes 

cc_p41 <- P4_1 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

cc_p42 <- P4_2 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p4cc_com <- cbind(cc_p41, cc_p42)
p4cc_com$mean <- rowMeans(p4cc_com)
p4cc_mean <- p4cc_com %>% rownames_to_column("Genes")

p4_cc <-  data.frame("Genes" = p4cc_mean$Genes, "FPKM" = p4cc_mean$FPKM, "Status"=c("P4", "P4","P4", "P4","P4"))
```


```{r}
#filter P7 cc 
cc_p71 <- P7_1 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

cc_p72 <- P7_2 %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

p7cc_com <- cbind(cc_p71, cc_p72)
p7cc_com$mean <- rowMeans(p7cc_com)
p7cc_mean <- p7cc_com %>% rownames_to_column("Genes")

p7_cc <-  data.frame("Genes" = p7cc_mean$Genes, "FPKM" = p7cc_mean$FPKM, "Status"=c("P7", "P7","P7", "P7","P7"))
```


```{r}
#filter Ad mitchondria 
cc_ad1 <- Ad1_ftable %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name") 
cc_ad2 <- Ad2_ftable %>% filter(gene_short_name %in% genes_cc) %>% select(gene_short_name, FPKM) %>% column_to_rownames("gene_short_name")

adcc_com <- cbind(cc_ad1, cc_ad2$FPKM)
adcc_com$mean <- rowMeans(adcc_com) 
adcc_mean <- adcc_com %>% rownames_to_column("Genes")
ad_cc <- data.frame("Genes" = adcc_mean$Genes, "FPKM" = adcc_mean$mean, "Status" = c("Ad", "Ad","Ad", "Ad","Ad","Ad", "Ad","Ad", "Ad","Ad"))
cc_fin <- bind_rows(p0_cc, p4_cc, p7_cc, ad_cc)
```


#Plots
```{r}
library(ggplot2)

#Sacromere
sac_fin$Status = as.factor(sac_fin$Status)
sac_fin$Status <- factor(sac_fin$Status, levels=c("P0", "P4", "P7","Ad"))
ggplot(sac_fin, aes(x=Status, y=FPKM, col=Genes, group=Genes)) +geom_point()+ geom_path()+labs(x="", y="FPKM")+scale_y_continuous(breaks=seq(100,1300,100)) +ggtitle("Sacromere")+theme(plot.title = element_text(hjust = 0.5))





#Mitochondria
mit_fin$Status = as.factor(mit_fin$Status)
mit_fin$Status <- factor(mit_fin$Status, levels=c("P0", "P4", "P7","Ad"))
ggplot(mit_fin, aes(x=Status, y=FPKM, col=Genes, group=Genes)) +geom_point()+ geom_path()+ scale_y_continuous(breaks=seq(0,280,50)) + theme(plot.title = element_text(hjust = 0.5))+ggtitle("Mitocondria")

#Cell Cycle
cc_fin$Status = as.factor(cc_fin$Status)
cc_fin$Status <- factor(cc_fin$Status, levels=c("P0", "P4", "P7","Ad"))
ggplot(cc_fin, aes(x=Status, y=FPKM, col=Genes, group=Genes)) +geom_point()+ geom_path()+ scale_y_continuous(breaks=seq(0,50,10)) + theme(plot.title = element_text(hjust = 0.5))+ggtitle("Cell Cycle")
```






```{r}

gdiff2 <- Gdiff %>% filter(Gdiff$significant == 'yes' & Gdiff$significant == 'yes' & Gdiff$log2.fold_change. !="Inf" & Gdiff$log2.fold_change. !="-Inf") %>% arrange(log2.fold_change.)

head500 <- gdiff2 %>% head(gdiff2[unique(gdiff2$gene),]$log2.fold_change., n=500)
tail500 <- gdiff2 %>% tail(gdiff2[unique(gdiff$gene),]$log2.fold_change., n=500)
diff1000 <- rbind(head500,tail500)

#1000 genes
diff1000df <- data.frame("Genes"=diff1000$gene, "log fold change" = diff1000$log2.fold_change.)
#diff1000_2 <- diff1000[, c(gene, "log2.fold_change.")]
```



```{r}
library(tidyverse)



#FPKM values


P01_fpkm <- P0_1 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P01_temp <- P01_fpkm[!duplicated(P01_fpkm$gene_short_name), ] %>% rename(P0_1 = FPKM)
#rownames(P01_temp) <- NULL
#P01_fin <- P01_temp %>% column_to_rownames("gene_short_name") %>% rename(P0_1 = FPKM)

P02_fpkm <- P0_2 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P02_temp <- P02_fpkm[!duplicated(P02_fpkm$gene_short_name), ] %>% rename(P0_2 = FPKM)

P42_fpkm <- P4_2 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P42_temp <- P42_fpkm[!duplicated(P42_fpkm$gene_short_name), ] %>% rename(P4_2 = FPKM)

P41_fpkm <- P4_1 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P41_temp <- P41_fpkm[!duplicated(P02_fpkm$gene_short_name), ] %>% rename(P4_1 = FPKM)

P71_fpkm <- P7_1 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P71_temp <- P71_fpkm[!duplicated(P71_fpkm$gene_short_name), ] %>% rename(P7_1 = FPKM)

P72_fpkm <- P7_2 %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
P72_temp <- P72_fpkm[!duplicated(P71_fpkm$gene_short_name), ] %>% rename(P7_2 = FPKM)

ad1_fpkm <- Ad1_ftable %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
ad1_temp <- ad1_fpkm[!duplicated(ad1_fpkm$gene_short_name), ] %>% rename(Ad_1 = FPKM)

ad2_fpkm <- Ad2_ftable %>% filter(gene_short_name %in% diff1000df$Gene) %>% select(gene_short_name,FPKM) 
ad2_temp <- ad2_fpkm[!duplicated(ad2_fpkm$gene_short_name), ] %>% rename(Ad_2 = FPKM)

#concatenated table
concat04 <- inner_join(P01_temp, P02_temp, by="gene_short_name") %>% inner_join(., P41_temp, by="gene_short_name") %>% inner_join(., P42_temp, by="gene_short_name") %>% inner_join(., P71_temp, by="gene_short_name") %>% inner_join(., P72_temp, by="gene_short_name") %>% inner_join(., ad1_temp, by="gene_short_name") %>% inner_join(., ad2_temp, by="gene_short_name")

concat_temp <- concat04[!duplicated(concat04$gene_short_name), ] 
rownames(concat_temp) <- NULL
concat_fin <- concat_temp %>% column_to_rownames("gene_short_name")


#heatmap

heatmap(as.matrix(concat_fin))
```














