#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

# make SRA tools available
Module load sratoolkit

# extract the SRA format to FASTQ (paired-end sequenceing)
fastq-dump --split-files /projectnb/bf528/users/group_5/project_2/samples/P0_1.sra -O /projectnb/bf528/users/group_5/project_2/samples

echo "Job finished: $(date +%F)"


